TAS-107 뱃지 API
LetMeDoWith/LetMeDoWith-BE pull request #21
Opened 2024-09-18 14:39 UTC by gyun-ky

## PR 체크리스트
Merge 전에 아래 체크리스트가 모두 체크되었는지 확인해주세요 

- [x] 마지막 commit전에 빌드하여 코드 스타일 점검하였나요?
- [ ] 최소 1명의 리뷰와 Approve를 받았나요?
- [x] 모든 Test 코드를 실행하여 PASS했나요?
- [x] 포스트맨 API 명세를 작성하였나요?

## PR 타입
PR의 타입을 체크해주세요

- [ ] 버그 픽스 - 이슈 링크 : 
- [x] 신규 기능 개발
- [ ] 기능 수정
- [ ] 테스트 코드 추가
- [ ] 코드 스타일 업데이트 (formatting, 변수명 수정 등)
- [ ] 리팩토링 (기능 수정은 없고 코드 재사용성을 위한 메서드 분리 등)
- [ ] 설정 파일 수정
- [ ] 기타

## 코드 변경 이유

- 이슈 링크 : TAS-107
- 뱃지 관련 API 개발

## 변경된 사항

API 기능에 대한 상세 사항은 POSTMAN DOC 참고 : https://documenter.getpostman.com/view/11468363/2sA3QmCuY9

### 뱃지 도메인 생성
- Badge / MemberBadge(member와 Badge의 다대다 테이블)을 하나의 Aggregate로 설정
- MemberBadge와 Member 간의 참조는 끊음
 
<img width="918" alt="스크린샷 2024-09-18 오후 11 30 40" src="https://github.com/user-attachments/assets/4935fbf8-7730-4c66-a2a7-4449996c6cc3">

### 뱃지 목록 조회 API
- 뱃지 UI 참고하여 UI에 Fit하게 Response DTO 매핑하는 것은 Presentation 레이어에서 진행
- 
#### 개발 중 이슈
조회 시, Entity로 조회한 것이 아니라 DTO로 조회
- 다 : 1 = Badge : MemberBadge에서 Left Join의 대상이 Badge인데, JPA Entity Graph는 데이터 일관성을 유지해야함 
- Query DSL Fetch Join으로 Badge 대상 Left Join시 에러 
- 이러한 케이스는 DTO로 Flat하게 조회 --> 이것때문에 오래 걸림
```
{
    "statusCode": "S100",
    "message": "요청에 성공했습니다.",
    "data": {
        "isLazyMember": false,
        "mainBadge": {
            "id": 1,
            "name": "뱃지1",
            "imageUrl": "https://contents.sixshop.com/uploadedFiles/84218/default/image_1547035192141.jpg",
            "description": "뱃지1 설명설명입니다. 뱃지는 설명이 필요하죠"
        },
        "badges": [
            {
                "id": 1,
                "isAcquired": true,
                "name": "뱃지1",
                "imageUrl": "https://contents.sixshop.com/uploadedFiles/84218/default/image_1547035192141.jpg",
                "description": "뱃지1 설명설명입니다. 뱃지는 설명이 필요하죠",
                "acquireHint": "뱃지1 획득 힌트 입니다. 뱃지2를 획득하려면 힌트가 필요하죠"
            },
            {
                "id": 2,
                "isAcquired": true,
                "name": "뱃지2",
                "imageUrl": "https://contents.sixshop.com/uploadedFiles/84218/default/image_1547035192141.jpg",
                "description": "뱃지2 설명설명입니다. 뱃지는 설명이 필요하죠",
                "acquireHint": "뱃지2 획득 힌트 입니다. 뱃지2를 획득하려면 힌트가 필요하죠"
            },
            {
                "id": 3,
                "isAcquired": false,
                "name": "뱃지3",
                "imageUrl": "https://contents.sixshop.com/uploadedFiles/84218/default/image_1547035192141.jpg",
                "description": "뱃지3 설명설명입니다. 뱃지는 설명이 필요하죠",
                "acquireHint": "뱃지3 획득 힌트 입니다. 뱃지2를 획득하려면 힌트가 필요하죠"
            },
            {
                "id": 4,
                "isAcquired": true,
                "name": "뱃지4",
                "imageUrl": "https://contents.sixshop.com/uploadedFiles/84218/default/image_1547035192141.jpg",
                "description": "뱃지4 설명설명입니다. 뱃지는 설명이 필요하죠",
                "acquireHint": "뱃지4 획득 힌트 입니다. 뱃지2를 획득하려면 힌트가 필요하죠"
            },
            {
                "id": 5,
                "isAcquired": false,
                "name": "뱃지5",
                "imageUrl": "https://contents.sixshop.com/uploadedFiles/84218/default/image_1547035192141.jpg",
                "description": "뱃지5 설명설명입니다. 뱃지는 설명이 필요하죠",
                "acquireHint": "뱃지5 획득 힌트 입니다. 뱃지2를 획득하려면 힌트가 필요하죠"
            },
            {
                "id": 6,
                "isAcquired": false,
                "name": "뱃지6",
                "imageUrl": "https://contents.sixshop.com/uploadedFiles/84218/default/image_1547035192141.jpg",
                "description": "뱃지6 설명설명입니다. 뱃지는 설명이 필요하죠",
                "acquireHint": "뱃지6 획득 힌트 입니다. 뱃지2를 획득하려면 힌트가 필요하죠"
            }
        ]
    }
}
```

### 대표 뱃지 등록/수정 API
- Member가 획득한 뱃지 (MemberBadge 테이블에 존재하는) `main_yn` 설정
- Member가 Lazy 뱃지 부여 받은 상태 (Member테이블의 `task_level` 참고)에서는 등록/수정 불가

## 테스트 방법

- 개발 시간상 테스트는 Repository Test, Integration Test 작성 및 테스트 완료
- 테스트 코드 작성시간을 어떻게 하면 줄일 수 있을지 한번 연구 필요

## 리뷰어 집중 사항

- Domain
- Query DSL

## 기타 전달 사항

- 
-

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/repository/BadgeRepository.java
> +  Optional<Badge> getBadge(Long badgeId, BadgeStatus badgeStatus);
`Bagde` 오브젝트가 static한 성격을 가지니까 중장기적으로 캐시를 통해 응답할 수 있는 방향으로 가는게 좋다고 생각합니다.
FE에서도 만약 `react-query`를 쓴다면 (RN에서 가능한지는 확인해봐야 함) 아예 FE에서 뱃지 목록을 캐싱하는 방법이 제일 좋겠네요.

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
> +        .orElseThrow(() -> new RestApiException(MEMBER_NOT_EXIST_BADGE));
현재 PR의 스코프를 벗어나는 내용이긴 하지만, 
`MemberStatus.NORMAL` 상태로 거의 대부분의 `Member`를 조회하게 될 것 같은데, `MemberService` 혹은 `MemberRepository`에 `getNormalStatusMember()` 같은 메서드를 정의하는 것은 어떻게 생각하시는지??

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
`Badge`를 새로 추가하거나 삭제하거나, 획득가능 여부를 변경하는 메서드는 아직 없는거죠?

그런 내용들은 엔드유저의 usecase는 아니니 `BadgeAdminService` 등으로 분리하여 개발하는것에 대해 어떻게 생각하시는지요?>?>?>?>

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
> +    memberBadge.registerToMainBadge();
Main badge에 대한 cancel과 register는 비즈니스 로직 상 무조건 한 요청 내에 이루어져야 하니 두개의 동작을 한개로 합치는게 나을 것 같다는 생각입니다. (cancel, register가 독립적인 비즈니스 로직으로 사용되는 usecase가 존재하지 않을 것으로 예측되기 때문)
```java
// Badge.java

@Entity
public class Badge {
    // atributes...

    public void cancelMainBadge() {
        // 메인 뱃지 취소
    }

    public void registerToMainBadge() {
        // 메인 뱃지 설정
    }


    // 기존 단위 로직은 살리고, 합성하여 복잡한 비즈니스 로직 도출
    public void changeMainBadgeTo(Badge next) {
        this.cancelMainBadge();
        next.registerToMainBadge();
    }
}
```

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/common/enums/member/TaskLevel.java
> +}
초록불 노란불 빨간불을 보고 이게 신호등이라는 걸 알았습니다. `TaskFulfillLevel` 같은 이름으로 조금 더 명확하게 가야 할 것 같습니다..

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/common/exception/status/FailResponseStatus.java
> +    MEMBER_NOT_EXIST_BADGE("MEMBER_BADGE_NOT_EXIST",
`E218: 존재하지 않는 회원입니다` 와 구별해야 하는 이유가 있나요?

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/domain/member/Badge.java
> +  }
지금 `BadgeStatus`를 서로 다르게 정의하고 있는 것 같습니다.

제가 생각하는 Active/Inactive의 정의입니다.
- `Active`: 현재 이 `Badge`는 획득 가능한 상태임
- `Inactive`: 이 `Badge`는 더 이상 획득 불가능함. (기간 한정으로 획득이 가능하다던지 등)

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/domain/member/Badge.java
> +  }
`Badge` 에서 유저가 내가 메인인지의 여부, 메인 설정과 관련한 연산을 정의할 필요가 있는지 의문입니다.
`MemberBadge`에서만 정의되어야 하는게 아닌가 싶은데,,,

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/infrastructure/member/jpaRepository/BadgeJpaRepository.java
> +  Optional<Badge> findByName(String name);
이러면 이름을 정확하게 입력해야 찾을 수 있다는 건데 활용하기 어려워보입니다.

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/infrastructure/member/jpaRepository/QBadgeJpaRepositoryImpl.java
> +        .orderBy(qBadge.sortOrder.asc())
`sortOrder` 값이 모든 `Badge`에 대해 유일함이 보장되어야 할 것 같은데, 순서에 대한 정책을 아주 잘 만들어야 할 것 같습니다.. 아니면 내부적으로 동일 순서 발생시 그 다음 정렬 순서는 어떻게 할지에 대해 결정해야 할 것 같구요,,,

2024-09-20 12:16 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/infrastructure/member/repository/BadgeRepositoryImpl.java
> +  }
`Badge`를 저장하면서 `MemberBadge`를 불러와서 저장한다는게 이해가 잘 안되는데 설명이 필요합니다.

2024-09-21 08:25 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/repository/BadgeRepository.java
> +  Optional<Badge> getBadge(Long badgeId, BadgeStatus badgeStatus);
넵넵 캐시는 개발시에 바로 달지는 않고 개발이 어느정도 완료되고,
호출을 분석해서 그때 일괄 적용하는게 좋을거 같습니다

2024-09-21 08:25 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
> +        .orElseThrow(() -> new RestApiException(MEMBER_NOT_EXIST_BADGE));
그게 나을거 같습니다 수정해놓을게요!

2024-09-21 08:26 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
네네 저도 그렇게 생각합니다! 해당 부분은 개발하지 않았습니다
1차는 유져 서비스 개발에 공수를 집중하고, 
어드민은 1차 오픈후에도 DB 직접 수정으로 일단 대응하시죠

2024-09-21 08:29 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
> +    memberBadge.registerToMainBadge();
아 이게 개발하다보니까 Badge가 Root Aggregate가 되면 안되더라고요
- 유져 플로우에서는 MemberBadge를 Root Aggregate로 하고
- 어드민 플로우에서는 Badge가 Root Aggregate

사실상 Admin 플로우에서는 Entity를 따로 두는게 맞음

MemberBadge 를 RootAggregate로 하고 다시 코드 정리한다음에 알려드릴게요

2024-09-21 08:31 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/common/enums/member/TaskLevel.java
> +}
TaskFulfillLevel 좋네요
저희 이행이란 단어는 Complete도 쓰고 있는걸로 알고 있는데
이럴때는 유비쿼터스 랭귀지로 하나 딱 정하고 Notion에 등록하는게 좋습니다
DB 스키마에서는 Complete를 쓰니까 이행 = Complete로 유비쿼터스 랭귀지 정하고
TaskCompleteLevel 어떠할까요?

2024-09-21 08:32 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/infrastructure/member/repository/BadgeRepositoryImpl.java
> +  }
요거 MemberBadge가 Root Aggregate가 되고 코드 수정하면 알려드리겠습니다

2024-09-21 08:33 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/infrastructure/member/jpaRepository/QBadgeJpaRepositoryImpl.java
> +        .orderBy(qBadge.sortOrder.asc())
네네 고런거는 나중에 어드민 사이트를 만든다면, 어플리케이션 단에서 중복되지 않게 해줄수 있을거 같네요
그전까지는 아주 유의하면서 DB 직접 조작

2024-09-21 08:34 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/infrastructure/member/jpaRepository/BadgeJpaRepository.java
> +  Optional<Badge> findByName(String name);
저 메서드 test코드를 위해 넣어놓은 메서드고요 JPA 표준이라서 저희가 네이밍명은 수정 못합니다
아시다시피, 메서드명보고 JPA가 쿼리를 만들어서요

2024-09-21 08:35 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/domain/member/Badge.java
> +  }
요거도 MemberBadge를 Root Aggregate로 설정후 코드 수정한다음에 알려드리겠습니다

2024-09-21 08:39 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/domain/member/Badge.java
> +  }
이것도 Badge를 Root Aggregate로 봤을 때, 유져의 입장에서 
- UI에서 활성화된 뱃지
- UI에서 비활성화된 뱃지

이걸 나타낸 거였습니다

Badge를 어드민 플로우에서 Root Aggregate로 본다면 저건 해당 유져의 뱃지가 활성화/비활성화 상태인지 를 판단하는 메서드가 될거 같습니다

2024-09-22 09:55 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/domain/member/Badge.java
> +  }
- 활성: 유저가 해당 뱃지를 획득함
- 비활성: 유저가 해당 뱃지를 아직 획득하지 못함

화면 설계서를 보니 활성/비활성의 정의가 이러한 듯 한데, 제가 맞게 이해한건가요?

2024-09-22 09:56 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/infrastructure/member/jpaRepository/BadgeJpaRepository.java
> +  Optional<Badge> findByName(String name);
LIKE 로 검색하도록 하는건 좋지못한생각일까요.?

2024-09-28 07:27 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/infrastructure/member/jpaRepository/BadgeJpaRepository.java
> +  Optional<Badge> findByName(String name);
SQL like 말씀하시는건가요?

2024-09-28 07:49 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
> +        .orElseThrow(() -> new RestApiException(MEMBER_NOT_EXIST_BADGE));
반영했습니다

2024-09-28 07:50 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
> +    memberBadge.registerToMainBadge();
MemberBadge를 Root로 해서 반영했습니다

2024-09-28 07:54 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/common/enums/member/TaskLevel.java
> +}
반영했습니다!

2024-09-28 07:56 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/common/exception/status/FailResponseStatus.java
> +    MEMBER_NOT_EXIST_BADGE("MEMBER_BADGE_NOT_EXIST",
추후에 모니터링을 위한 로깅 시에 어느 API에서 발생했는지 찾을려는 목표였는데 생각해보니, API 도 로그에 찍히니 저럴 필요가 없을거 같습니다

이런 에러들은 도메인 단위로 묶는거로 하시져
MemberRepository에서 발생하는 에러 -> Member 하위 에러로

2024-09-28 08:01 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/infrastructure/member/repository/BadgeRepositoryImpl.java
> +  }
반영했습니다

2024-09-28 08:11 UTC, S-J-Kim requested changes

2024-09-28 08:11 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
> +  }
메서드 단위로 주석을 달아야 할 것 같습니다... 이 메서드도 뱃지 정보를 가져올때 마지막에 lazy까지 체크하니까 주석으로 간략하게나마 설명이 있어야 할 것으로 보이네요..

2024-09-28 08:11 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/infrastructure/member/jpaRepository/BadgeJpaRepository.java
> +  Optional<Badge> findByName(String name);
ㄴㅔ 맞습니다..

2024-09-28 08:11 UTC, S-J-Kim commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
> +  }
`save()`가 없는거 같아보입니다...?

2024-09-28 08:20 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
> +  }
JPA 변경감지에 의해서 save됩니다!

2024-09-28 08:21 UTC, gyun-ky commented on src/main/java/com/LetMeDoWith/LetMeDoWith/application/member/service/BadgeService.java
> +  }
주석 추가 했습니다

2024-10-01 06:06 UTC, merged